version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image: # Builds the image based on the Dockerfile instructions and pushes it to ECR
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: CANARY-DEPLOYMENT-TEST
          repo: $AWS_ECR_REPO_NAME
          region: AWS_DEFAULT_REGION
          tag: $CIRCLE_SHA1
          # nothing more